
ATF_SRC = "${MAAXBOARD_GIT_HOST_MIRROR}/imx-atf.git;${MAAXBOARD_GIT_PROTOCOL}"
SRCBRANCH = "maaxboard_lf-5.15.71-2.2.0"
SRC_URI = "${ATF_SRC};branch=${SRCBRANCH}"
SRCREV = "${AUTOREV}"

ATF_BOOT_UART_BASE = "0x30860000"
